#!/usr/bin/env python3
"""Offline, manifest-fixed defense analysis and synchronization of paper tables.

No log discovery by mtime, model calls, or human-label changes. The evaluator is
held fixed; its hash and every input hash are recorded for reproducibility.
"""
from __future__ import annotations

import hashlib
import importlib.util
import json
import subprocess
import tempfile
from collections import Counter
from pathlib import Path

import audit_scorer_credibility as audit
from bootstrap_ci import METRICS, bootstrap, summarize
from build_defense_paired_analysis import (
    ROOT, DEFAULT_MANIFEST, load_runs, build_exposure, build_paired,
    paired_success, read_csv, read_jsonl, write_csv,
)
from evaluator import aggregate
from summarize_results import write_overall
import random

RESULTS = ROOT / "toxictool_bench/results"
SECTIONS = ROOT / "sections"
PREFIX = "leakage_free_defense"
LEGACY_COMMIT = "f0aa054dccc9437dcf89f0b22a01825e2772be66"
NAMES = {
    "langgraph_react_full": "Base",
    "langgraph_react_double_pass": "Double-pass",
    "langgraph_react_verification_only": "Verification only",
    "langgraph_react_guarded": "Generic guard",
}
SUITES = {"numerical_iclr2027": "Numerical", "semantic_schema_iclr2027": "Semantic/schema"}
GUARD = "langgraph_react_guarded"
BEHAVIOR = {"BCR": "blind_compliance", "PAR": "poison_adoption", "VPA": "validated_poison_adoption", "VR": "validation", "RR": "recovery"}


def table_rows(path: Path, label: str, lines: list[str]) -> None:
    """Replace only the body of the uniquely labelled table, preserving prose."""
    text = path.read_text()
    token = "\\label{" + label + "}"
    if text.count(token) != 1:
        raise ValueError(f"Expected exactly one {label} in {path}")
    pos = text.index(token)
    start = text.rindex("\\begin{table}", 0, pos)
    body = text.index("\\midrule", start) + len("\\midrule")
    end = text.index("\\bottomrule", body)
    if end > pos:
        raise ValueError(f"Malformed table {label}")
    generated = "\n% Generated by toxictool_bench/sync_defense_paper.py; do not edit numbers.\n"
    path.write_text(text[:body] + generated + "\n".join(lines) + "\n" + text[end:])


def line(*values) -> str:
    return " & ".join(map(str, values)) + r" \\"


def f(value, digits=2) -> str:
    return f"{float(value):.{digits}f}"


def ci(row, digits=3) -> str:
    return f"[{f(row['ci95_lo'], digits)}, {f(row['ci95_hi'], digits)}]"


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def suite_table_lines(summaries, exposure):
    """Combined suite outcomes and delivery denominators in the short appendix."""
    exp = {(r['suite'], r['adapter']): r for r in exposure}
    return [line(
        'Numerical' if s == 'numerical_iclr2027' else 'Semantic', NAMES[a],
        *[summaries[s][a][k] for k in
          ('clean_tsr', 'poisoned_tsr', 'toxic_bcr', 'toxic_vr', 'toxic_rr')],
        f"{exp[s,a]['n_exposed']}/{exp[s,a]['n_toxic']}", f(exp[s,a]['pdr'], 3),
    ) for s in SUITES for a in NAMES]


def audit_table_lines(consensus, agreement):
    """Keep scorer accuracy distinct from pre-adjudication rater agreement."""
    return [line(k.upper(), r['n_evaluated'], f(r['precision'], 3),
                 f(r['recall'], 3), f(r['f1'], 3),
                 f(agreement[k]['percent_agreement'], 3),
                 f(agreement[k]['cohen_kappa'], 3))
            for k, r in consensus.items()]


def main() -> None:
    runs = load_runs(DEFAULT_MANIFEST)
    if set(key[0] for key in runs) != set(SUITES):
        raise ValueError("Expected the two registered defense suites")
    if any(len(group) != (58 if key[0]=='numerical_iclr2027' else 60) for key, group in runs.items()):
        raise ValueError("Expected 58 numerical / 60 semantic task IDs after reference exclusions")
    toxic = {(suite, adapter): rows for (suite, adapter, env), rows in runs.items() if env == "toxic"}
    exposure = build_exposure(toxic)
    paired = build_paired(toxic, 13)
    interaction = paired_success(runs, 13)
    write_csv(RESULTS / f"{PREFIX}_exposure_denominators.csv", exposure)
    write_csv(RESULTS / f"{PREFIX}_paired_ci.csv", paired)
    write_csv(RESULTS / f"{PREFIX}_success_interaction.csv", interaction)
    summaries, intervals = {}, {}
    all_rows = [row for group in runs.values() for row in group.values()]
    for suite in [*SUITES, "combined"]:
        rows = [row for (s, _, _), group in runs.items() if suite == "combined" or suite == s for row in group.values()]
        summary_path = RESULTS / f"{PREFIX}_{suite}_summary.csv"
        write_overall(rows, summary_path)
        summaries[suite] = {row["adapter"]: row for row in read_csv(summary_path)}
        ci_rows = []
        for i, adapter in enumerate(sorted(NAMES)):
            selected = [row for row in rows if row["adapter"] == adapter]
            point = summarize(selected)
            boot = bootstrap(selected, 5000, random.Random(13 + i))
            result = {"model": selected[0]["model"], "adapter": adapter,
                      "n_tasks": len(selected) // 2,
                      "n_exposed": aggregate([row for row in selected if row['environment'] == 'toxic'])["n_exposed"]}
            for metric in METRICS:
                result.update({metric: f(point[metric], 4), f"{metric}_lo": f(boot[metric][0], 4), f"{metric}_hi": f(boot[metric][1], 4)})
            ci_rows.append(result)
            intervals[(suite, adapter)] = result
        write_csv(RESULTS / f"{PREFIX}_{suite}_bootstrap_ci.csv", ci_rows)
    # Row-level checks precede any manuscript mutation.
    selection_rows = []
    for (suite, adapter, env), group in sorted(runs.items()):
        counts = Counter(row["metrics"]["answer_selection"] for row in group.values())
        for row in group.values():
            m = row["metrics"]
            assert int(m["blind_compliance"]) + int(m["validated_poison_adoption"]) <= int(m["poison_adoption"])
            assert not m["recovery"] or m["task_success"]
        selection_rows.append({"suite": suite, "adapter": adapter, "environment": env,
                               "n": len(group), **{name: counts[name] for name in ("clean", "poisoned", "ambiguous", "unresolved")}})
    write_csv(RESULTS / f"{PREFIX}_answer_selection_counts.csv", selection_rows)
    # Re-evaluate the existing consensus packet, without changing human labels.
    manifest_rows = audit.read_csv(audit.DEFAULT_MANIFEST)
    consensus_rows = audit.rescore_audit_rows(audit.read_csv(audit.DEFAULT_AUDIT), audit.load_tasks(manifest_rows))
    consensus = {key: audit.classification_report(consensus_rows, key) for key in audit.LABELS}
    (RESULTS / "scorer_consensus_validation.json").write_text(json.dumps({"scorer_sha256": sha(ROOT / "toxictool_bench/evaluator.py"), "n": len(consensus_rows), "independent_holdout": False, "metrics": consensus}, indent=2) + "\n")
    # Compare two actual evaluators on identical trajectories, never rounded
    # summary files or a moving HEAD reference.
    legacy_source = subprocess.check_output(["git", "show", f"{LEGACY_COMMIT}:toxictool_bench/evaluator.py"], cwd=ROOT, text=True)
    task_defs = {s: {t['task_id']: t for t in read_jsonl(ROOT / f"toxictool_bench/tasks/{s}.jsonl")} for s in SUITES}
    legacy_rows = []
    with tempfile.TemporaryDirectory() as tmp:
        legacy_path = Path(tmp) / "legacy_evaluator.py"
        legacy_path.write_text(legacy_source)
        spec = importlib.util.spec_from_file_location("legacy_evaluator", legacy_path)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        for (suite, _, _), group in runs.items():
            for row in group.values():
                legacy_rows.append({**row, "metrics": module.evaluate_run(task_defs[suite][row['task_id']], row['final_answer'], row['tool_events'])})
    impacts = []
    for adapter in NAMES:
        old = summarize([r for r in legacy_rows if r['adapter'] == adapter])
        new = summarize([r for r in all_rows if r['adapter'] == adapter])
        for metric in ("clean_tsr", "toxic_tsr", "toxic_bcr", "toxic_par", "toxic_vpa", "toxic_vr", "toxic_rr"):
            impacts.append({"adapter": adapter, "metric": metric, "legacy_commit": LEGACY_COMMIT,
                            "old_value": f(old[metric], 6), "revised_value": f(new[metric], 6), "delta": f(new[metric]-old[metric], 6)})
    write_csv(RESULTS / f"{PREFIX}_scorer_revision_impact.csv", impacts)
    appendix = SECTIONS / "08_appendix_guard_details.tex"
    scoring_appendix = SECTIONS / "09_revision_validation.tex"
    agreement_path = ROOT / "toxictool_bench/human_audit_v2/agreement.json"
    agreement = json.loads(agreement_path.read_text())["labels"]
    # Main results, suite breakdown, counts, audit, paired inference and CIs all
    # come from the objects above, not independently typed manuscript values.
    table_rows(SECTIONS / "05_experiments.tex", "tab:langgraph-guarded", [
        line(NAMES[a], *[summaries['combined'][a][k] for k in ('clean_tsr','poisoned_tsr','toxic_bcr','toxic_par','toxic_vpa','toxic_vr','toxic_rr')], summaries['combined'][a]['n_exposed']) for a in NAMES])
    table_rows(appendix, "tab:appendix-guard-suite-breakdown",
               suite_table_lines(summaries, exposure))
    exp = {(r['suite'],r['adapter']):r for r in exposure}
    table_rows(scoring_appendix, "tab:appendix-scorer-precision",
               audit_table_lines(consensus, agreement))
    paired_lines = []
    for suite in [*SUITES, "combined"]:
        for r in interaction:
            if r['suite'] == suite:
                name = {"clean_tsr":"Clean TSR", "poisoned_tsr":"Poisoned TSR", "clean_adjusted_tsr_delta":r"$\Delta_{\mathrm{interaction}}$"}[r['metric']]
                paired_lines.append(line(SUITES.get(suite,"Combined"),name,r['n_paired'],f"{float(r['mean_delta']):+.3f}",ci(r)))
        if suite != 'combined':
            for r in paired:
                if r['suite']==suite and r['treatment']==GUARD and r['metric'] in ('BCR','validation','recovery'):
                    paired_lines.append(line(SUITES[suite],{'validation':'VR','recovery':'RR'}.get(r['metric'],r['metric']),r['n_paired'],f"{float(r['mean_delta']):+.3f}",ci(r)))
    table_rows(appendix, "tab:appendix-paired-defense-ci", paired_lines)
    interval_lines = []
    for s in SUITES:
        for a in NAMES:
            r = intervals[s,a]
            blo, bhi = float(r['toxic_bcr_lo']), float(r['toxic_bcr_hi'])
            if exp[s,a]['bcr_events'] == 0:
                # One-sided exact binomial upper bound on detected-event rate.
                blo, bhi = 0., 1 - .05 ** (1/int(r['n_exposed']))
            interval_lines.append({
                'suite': s, 'adapter': a,
                'poisoned_tsr_lo': r['toxic_tsr_lo'],
                'poisoned_tsr_hi': r['toxic_tsr_hi'],
                'bcr_lo': blo, 'bcr_hi': bhi,
                'bcr_interval': 'one_sided_exact' if exp[s,a]['bcr_events'] == 0 else 'bootstrap',
            })
    # Full marginal intervals stay available outside the compact paper; do not
    # update the immutable pre-reorganization TeX archive.
    write_csv(RESULTS / f"{PREFIX}_paper_intervals.csv", interval_lines)
    table_rows(scoring_appendix, "tab:appendix-scorer-revision-impact", [
        line(NAMES[a], *[f"{f(next(r for r in impacts if r['adapter']==a and r['metric']==m)['old_value'])}$\\to${f(next(r for r in impacts if r['adapter']==a and r['metric']==m)['revised_value'])}" for m in ('clean_tsr','toxic_tsr','toxic_bcr','toxic_par','toxic_vpa','toxic_vr','toxic_rr')]) for a in NAMES])
    inputs = {DEFAULT_MANIFEST, ROOT / "toxictool_bench/evaluator.py", Path(__file__), ROOT / "toxictool_bench/build_defense_paired_analysis.py", audit.DEFAULT_AUDIT}
    inputs.add(agreement_path)
    inputs.update(ROOT / 'toxictool_bench' / name for name in (
        'answer_selection.py', 'audit_reference_answers.py', 'results/reference_answer_audit.json'))
    inputs.update(ROOT / row['path'] for row in read_csv(DEFAULT_MANIFEST))
    inputs.update(ROOT / row['source_file'] for row in audit.read_csv(audit.DEFAULT_AUDIT))
    inputs.update(ROOT / path for row in manifest_rows for path in row['tasks'].split(';'))
    missing = sorted({row['source'] for row in manifest_rows if not (ROOT / row['source']).exists()})
    provenance = {"analysis_base_commit":"ee2e15f", "legacy_scorer_commit":LEGACY_COMMIT,
                  "paired_bootstrap_seed":13, "bootstrap_iterations":5000,
                  "combined_paired_bootstrap":"task resampling within each suite, preserving four outcomes",
                  "n_defense_trajectories":len(all_rows), "n_audit_trajectories":len(consensus_rows),
                  "missing_sources_in_other_paper_experiments":missing,
                  "sha256":{str(p.relative_to(ROOT)):sha(p) for p in sorted(inputs)}}
    (RESULTS / f"{PREFIX}_analysis_provenance.json").write_text(json.dumps(provenance,indent=2)+"\n")
    print(f"Synced defense tables from {len(all_rows)} trajectories and {len(consensus_rows)} existing audit labels.")
    print(f"Other paper-manifest sources unavailable locally: {len(missing)} (not reconstructed).")


if __name__ == "__main__":
    main()
